# Generated by Django 4.2.6 on 2024-04-22 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPawmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dono', models.CharField(max_length=100)),
                ('cidade_dono', models.CharField(max_length=100)),
                ('estado_dono', models.CharField(max_length=100)),
                ('pais_dono', models.CharField(max_length=100)),
                ('telefone_dono', models.CharField(max_length=15)),
                ('nome_animal', models.CharField(max_length=100)),
                ('idade_animal', models.IntegerField()),
                ('raca_animal', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
